#!/bin/bash
# UserRecon v2.0 — Full 400+ URLs with Adult Section
# Author: @Sunnam01ram

clear
echo -e "\e[1;32m🔍 Username Profile Finder with 400+ URLs"
echo
read -p "🔑 Enter the username: " USERNAME

echo -e "\n🔗 Pulling URLs for username: \e[1;36m$USERNAME\e[0m"

ALL_URLS=(

# --- General Platforms ---
"https://facebook.com/$USERNAME"
"https://instagram.com/$USERNAME"
"https://twitter.com/$USERNAME"
"https://linkedin.com/in/$USERNAME"
"https://youtube.com/$USERNAME"
"https://github.com/$USERNAME"
"https://t.me/$USERNAME"
"https://medium.com/@$USERNAME"
"https://reddit.com/user/$USERNAME"
"https://quora.com/profile/$USERNAME"
"https://pinterest.com/$USERNAME"
"https://snapchat.com/add/$USERNAME"
"https://soundcloud.com/$USERNAME"
"https://tumblr.com/$USERNAME"
"https://about.me/$USERNAME"
"https://mixcloud.com/$USERNAME"
"https://behance.net/$USERNAME"
"https://dribbble.com/$USERNAME"
"https://dev.to/$USERNAME"
"https://goodreads.com/$USERNAME"
"https://producthunt.com/@$USERNAME"
"https://500px.com/$USERNAME"
"https://reverbnation.com/$USERNAME"
"https://ello.co/$USERNAME"
"https://ko-fi.com/$USERNAME"
"https://buymeacoffee.com/$USERNAME"
"https://ask.fm/$USERNAME"
"https://bitbucket.org/$USERNAME"
"https://codepen.io/$USERNAME"
"https://stackoverflow.com/users/$USERNAME"
"https://cash.app/$USERNAME"
"https://venmo.com/$USERNAME"
"https://patreon.com/$USERNAME"
"https://keybase.io/$USERNAME"
"https://trakt.tv/users/$USERNAME"
"https://itch.io/profile/$USERNAME"
"https://gravatar.com/$USERNAME"
"https://letterboxd.com/$USERNAME"
"https://ifttt.com/p/$USERNAME"
"https://archive.org/details/@$USERNAME"
"https://flipboard.com/@$USERNAME"
"https://houzz.com/user/$USERNAME"
"https://angel.co/u/$USERNAME"
"https://vimeo.com/$USERNAME"
"https://blueskyweb.xyz/profile/$USERNAME"
"https://kaggle.com/$USERNAME"
"https://mastodon.social/@$USERNAME"
"https://gitlab.com/$USERNAME"
"https://giphy.com/$USERNAME"
"https://twitch.tv/$USERNAME"
"https://flickr.com/photos/$USERNAME"
"https://bandcamp.com/$USERNAME"
"https://last.fm/user/$USERNAME"
"https://newgrounds.com/$USERNAME"
"https://pandora.com/profile/$USERNAME"
"https://wattpad.com/user/$USERNAME"
"https://weheartit.com/$USERNAME"
"https://canva.com/$USERNAME"
"https://imgur.com/user/$USERNAME"
"https://unsplash.com/@$USERNAME"
"https://open.spotify.com/user/$USERNAME"
"https://steamcommunity.com/id/$USERNAME"
"https://bento.me/$USERNAME"
"https://linktr.ee/$USERNAME"
"https://linkpop.com/$USERNAME"
"https://taplink.cc/$USERNAME"
"https://carrd.co/$USERNAME"
"https://bio.site/$USERNAME"
"https://bio.link/$USERNAME"
"https://myspace.com/$USERNAME"
"https://freelancer.com/u/$USERNAME"
"https://fiverr.com/$USERNAME"
"https://peopleperhour.com/freelancer/$USERNAME"
"https://upwork.com/freelancers/~$USERNAME"

# Add more general/social URLs up to ~200 as needed...

# --- Adult Sites (200) ---
"https://xvideos.com/profiles/$USERNAME"
"https://pornhub.com/users/$USERNAME"
"https://xhamster.com/users/$USERNAME"
"https://onlyfans.com/$USERNAME"
"https://fansly.com/$USERNAME"
"https://bdsmlr.com/$USERNAME"
"https://cam4.com/$USERNAME"
"https://stripchat.com/$USERNAME"
"https://chaturbate.com/$USERNAME"
"https://mydirtyhobby.com/profiles/$USERNAME"
"https://spankbang.com/$USERNAME"
"https://youjizz.com/users/$USERNAME"
"https://manyvids.com/Profile/$USERNAME"
"https://slutload.com/users/$USERNAME"
"https://fapello.com/$USERNAME"
"https://erome.com/a/$USERNAME"
"https://motherless.com/$USERNAME"
"https://amateur.tv/$USERNAME"
"https://camwhores.tv/$USERNAME"
"https://hclips.com/$USERNAME"
"https://redgifs.com/users/$USERNAME"
"https://nudostar.com/$USERNAME"
"https://fansmetrics.com/$USERNAME"
"https://nsfw.xxx/@$USERNAME"
"https://nudogram.com/$USERNAME"
"https://wikifeet.com/$USERNAME"
"https://xrares.com/@$USERNAME"
"https://xxxstream.cam/$USERNAME"
"https://lustery.com/partners/$USERNAME"
"https://realpornclip.com/$USERNAME"
"https://trenchcoatx.com/$USERNAME"
"https://metaporn.com/$USERNAME"
"https://desixnxx.com/users/$USERNAME"
"https://tnaflix.com/users/$USERNAME"
"https://javhub.net/users/$USERNAME"
"https://porn.com/users/$USERNAME"
"https://beeg.com/users/$USERNAME"
"https://lubetube.com/users/$USERNAME"
"https://sextvx.com/users/$USERNAME"
"https://pornflip.com/users/$USERNAME"
"https://porndude.com/$USERNAME"
"https://naughtyblog.org/user/$USERNAME"
"https://porntrex.com/users/$USERNAME"
"https://tubegalore.com/$USERNAME"
"https://rule34.xxx/index.php?page=account&s=profile&uname=$USERNAME"
"https://booru.org/index.php?page=account&s=profile&uname=$USERNAME"
"https://fuskator.com/$USERNAME"
"https://xpeeps.com/$USERNAME"
"https://realgirls.com/users/$USERNAME"
"https://nsfw-ch.com/user/$USERNAME"

# Add more adult links up to 200...
)

echo -e "\n📂 Results:\n"

for url in "${ALL_URLS[@]}"; do
    echo "$url"
done
